"""update user to add otp and otp_expiration fields

Revision ID: 141c21b12dc8
Revises: 336bcfc6b265
Create Date: 2026-06-24 16:56:35.012290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '141c21b12dc8'
down_revision = '336bcfc6b265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_password_otp', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('reset_password_otp_expires', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_password_otp_expires')
        batch_op.drop_column('reset_password_otp')

    # ### end Alembic commands ###
