"""media-file relation-user:allow nullables

Revision ID: a4bff2551f9b
Revises: eaba147b5c8e
Create Date: 2026-06-08 17:37:58.775327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4bff2551f9b'
down_revision = 'eaba147b5c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.alter_column('create_by',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.alter_column('create_by',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
