"""media-file relation-user + default-relaiton-status

Revision ID: eaba147b5c8e
Revises: e1944ad8ca16
Create Date: 2026-06-08 16:22:16.868654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaba147b5c8e'
down_revision = 'e1944ad8ca16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_by', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('public_id', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('url', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('optimized_url', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('width', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('format', sa.String(length=50), nullable=True))
        batch_op.alter_column('submission_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'users', ['create_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('submission_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('format')
        batch_op.drop_column('duration')
        batch_op.drop_column('height')
        batch_op.drop_column('width')
        batch_op.drop_column('optimized_url')
        batch_op.drop_column('url')
        batch_op.drop_column('public_id')
        batch_op.drop_column('provider')
        batch_op.drop_column('create_by')

    # ### end Alembic commands ###
